# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]
        include:
          - os: ubuntu-22.04
            arch: linux-x64
          - os: windows-2022
            arch: win-x64
          - os: macos-11
            arch: osx-x64
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish -c Release -o ./output
    - name: Publish shared library
      if: matrix.arch != 'osx-x64'
      run: dotnet publish /p:NativeLib=Shared -c Release -o ./output

    - uses: actions/upload-artifact@v3
      with:
        name: GetAssemblyInfo-${{ matrix.arch }}
        path: |
          ${{ github.workspace }}/output/GetAssemblyInfo
          ${{ github.workspace }}/output/GetAssemblyInfo.exe

    - uses: actions/upload-artifact@v3
      if: matrix.arch != 'osx-x64'
      with:
        name: GetAssemblyInfo-${{ matrix.arch }}-shared
        path: |
          ${{ github.workspace }}/output/GetAssemblyInfo.dll
          ${{ github.workspace }}/output/GetAssemblyInfo.so
